/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated', dirName: '.'
    },
    {
      type: 'category',
      label: 'Lyfebloc Network',
      items: [
        {
          type: 'category',
          label: 'Important Links',
          items: [
            {
              type: 'link',
              label: 'Lyfebloc Network',
              href: 'https://lyfeblocnetwork.com/'
            },
            {
              type: 'category',
              label: 'Protocols',
              items: [
                {
                  type: 'link',
                  label: 'Automatic Protocol',
                  href: 'https://automaticprotocol.com/'
                },
                {
                  type: 'link',
                  label: 'Multiplier Protocol',
                  href: 'https://multiplierprotocol.com/'
                },
                {
                  type: 'link',
                  label: 'Deflationary Protocol',
                  href: 'https://deflationaryprotocol.com/'
                },
                {
                  type: 'link',
                  label: 'Whitepaper',
                  href: 'https://github.com/Lyfebloc/whitepaper/blob/main/Whitepaper.pdf'
                },
                {
                  type: 'link',
                  label: 'Trademark Policy',
                  href: 'https://lyfeblocnetwork.com/trademark'
                }
              ],
            },
            {
              type: 'category',
              label: 'Lyfebloc Exchange',
              items: [
                {
                  type: 'link',
                  label: 'Website',
                  href: 'https://lyfebloc.com/'
                },
                {
                  type: 'link',
                  label: 'Markets',
                  href: 'https://markets.lyfebloc.com/'
                },
                {
                  type: 'link',
                  label: 'Purchase Crypto',
                  href: 'https://pay.lyfebloc.com/pay.php?checkout_id=custom-123&price=0&external_reference=ABC'
                },
                {
                  type: 'link',
                  label: 'CryptoSwap Wallet',
                  href: 'https://cryptoswapwallet.com/'
                },
                {
                  type: 'link',
                  label: 'Orderbook Dex',
                  href: 'https://trade.lyfebloc.com/exchange/dashboard'
                }
              ],
            },
            {
              type: 'link',
              label: 'Mobile Apps',
              href: 'https://lyfeblocnetwork.com/apps'
            },
            {
              type: 'category',
              label: 'Company Websites',
              items: [
                {
                  type: 'link',
                  label: 'Coastal Media Brand',
                  href: 'https://coastalmediabrand.com/'
                },
                {
                  type: 'link',
                  label: 'Lyfeloop',
                  href: 'https://lyfeloop.com/'
                },
                {
                  type: 'link',
                  label: 'Justin Malonson',
                  href: 'https://justinmalonson.com/'
                }
              ]
            }
          ]
        },
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
